### ISSUE TITLE
use option -std=c99 or -std=gnu99 to compile your code

### ISSUE THREAD

**Issue by viswanadh401** [fabio-d/xc16plusplus#2]
I installed MPLAB X IDE 4.2 and XC16 1.35 in my windows PC. On writting a for loop the console showing the following error.

newmain.c:34:5: error: 'for' loop initial declarations are only allowed in C99 mode
newmain.c:34:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [build/default/production/newmain.o] Error 255
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2

How to solve this.?

**Comment by fabio-d** [comment]
I'm afraid there are some issues with your setup:
1) XC16 1.35 is not supported by XC16++ (see https://github.com/fabio-d/xc16plusplus/releases - only 1.23, 1.24 and 1.25 are supported).
2) It seems you have not installed XC16++ at all, but only XC16 (have a look at this project's README, section "Installation on top of an existing XC16 installation from binary packages").
3) MPLAB IDE does not support C++ (maybe you can workaround this issue by editing the Makefile or creating a custom one - you can have a look at https://github.com/fabio-d/xc16plusplus/blob/master/example-project/Makefile to get an idea).

If, on the other hand, you just want to be able to write "for (int i = 0; ...)" in a *C* program, I am sure there must some way to set -std=gnu99 somewhere in your XC16 (C compiler) flags (in other words, you don't need XC16++ for that).
